export default {
  montserrat: {
    black: "Montserrat-Black",
    blackItalic: "Montserrat-BlackItalic",
    bold: "Montserrat-Bold",
    boldItalic: "Montserrat-BoldItalic",
    extraBold: "Montserrat-ExtraBold",
    extraBoldItalic: "Montserrat-ExtraBoldItalic",
    extraLight: "Montserrat-ExtraLight",
    extraLightItalic: "Montserrat-ExtraLightItalic",
    italic: "Montserrat-Italic",
    light: "Montserrat-Light",
    lightItalic: "Montserrat-LightItalic",
    medium: "Montserrat-Medium",
    mediumItalic: "Montserrat-MediumItalic",
    regular: "Montserrat-Regular",
    semiBold: "Montserrat-SemiBold",
    semiBoldItalic: "Montserrat-SemiBoldItalic",
    thin: "Montserrat-Thin",
    thinItalic: "Montserrat-ThinItalic",
  },
  inter: {
    black: "Inter-Black",
    blackItalic: "Inter-BlackItalic",
    bold: "Inter-Bold",
    boldItalic: "Inter-BoldItalic",
    extraBold: "Inter-ExtraBold",
    extraBoldItalic: "Inter-ExtraBoldItalic",
    extraLight: "Inter-ExtraLight",
    extraLightItalic: "Inter-ExtraLightItalic",
    italic: "Inter-Italic",
    light: "Inter-Light",
    lightItalic: "Inter-LightItalic",
    medium: "Inter-Medium",
    mediumItalic: "Inter-MediumItalic",
    regular: "Inter-Regular",
    semiBold: "Inter-SemiBold",
    semiBoldItalic: "Inter-SemiBoldItalic",
    thin: "Inter-Thin",
    thinItalic: "Inter-ThinItalic",
  },
};
